using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HL.Brainwashing.HypnotizedPopup;

[GenerateTypedNameReferences]
public sealed partial class HypnotizedPopup : FancyWindow
{
    public HypnotizedPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AcknowledgeButton.OnPressed += _ => Close();
    }
}

