using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HL.Brainwashing.CompulsionsUI;

[GenerateTypedNameReferences]
public sealed partial class CompulsionDisplay : Control
{
    public CompulsionDisplay(string compulsion)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CompulsionLabel.SetMarkup(compulsion);
    }
}
