using Content.Shared._NF.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Content.Shared.Atmos;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Text;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._NF.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly ButtonGroup _buttonGroup = new();

    private const string IndentedNewline = "\n   ";

    public PlantAnalyzerWindow(PlantAnalyzerBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();

        OnButton.Group = _buttonGroup;
        OnButton.ToggleMode = true;
        OffButton.Group = _buttonGroup;
        OffButton.ToggleMode = true;

        OnButton.OnPressed += _ => owner.AdvPressed(true);
        OffButton.OnPressed += _ => owner.AdvPressed(false);
    }

    public void Populate(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        try
        {
            var target = _entityManager.GetEntity(msg.TargetEntity);
            Title = Loc.GetString("plant-analyzer-interface-title");

        // The net-entity for the scanned target may not be known on the client
        // the very first frame the UI opens. Populate the UI regardless of
        // whether we can resolve the entity; fall back to showing data from
        // the message itself. Only hide the data if the message contains no
        // useful information.
        NoData.Visible = false;

        if (msg.AdvancedInfo is not null)
        {
            OnButton.Pressed = true;
        }
        else
        {
            OffButton.Pressed = true;
        }

        // Process message fields into strings.
        StringBuilder chemString = new();
        if (msg.SeedChem != null)
        {
            foreach (var chem in msg.SeedChem)
            {
                chemString.Append(IndentedNewline);
                chemString.Append(chem);
            }
        }

        var isAdvanced = msg.AdvancedInfo != null;

        // Build exude/consume lists. When not advanced, show only gas names.
        // When advanced, show gas name plus rate if a rate exists, otherwise show name.
        StringBuilder exudeGases = new();
        StringBuilder consudeGases = new();

        // Helper to append a gas line based on advanced mode and available rates.
        void AppendGasLine(StringBuilder sb, Gas gas, float? rate)
        {
            sb.Append(IndentedNewline);
            if (isAdvanced && rate.HasValue)
                sb.Append($"{GetGasName(gas)}: {rate.Value:F2}");
            else
                sb.Append(GetGasName(gas));
        }

        // Map rates for quick lookup
        var exudeRatesMap = msg.ExudeGasRates?.ToDictionary(x => x.Gas, x => (float?)x.Rate) ?? new Dictionary<Gas, float?>();
        var consumeRatesMap = msg.ConsumeGasRates?.ToDictionary(x => x.Gas, x => (float?)x.Rate) ?? new Dictionary<Gas, float?>();

        // Iterate known gas flags and append if present
        foreach (var gas in new[] { Gas.Nitrogen, Gas.Oxygen, Gas.CarbonDioxide, Gas.Plasma, Gas.Tritium, Gas.WaterVapor, Gas.Ammonia, Gas.NitrousOxide, Gas.Frezon })
        {
            var flag = gas switch
            {
                Gas.Nitrogen => GasFlags.Nitrogen,
                Gas.Oxygen => GasFlags.Oxygen,
                Gas.CarbonDioxide => GasFlags.CarbonDioxide,
                Gas.Plasma => GasFlags.Plasma,
                Gas.Tritium => GasFlags.Tritium,
                Gas.WaterVapor => GasFlags.WaterVapor,
                Gas.Ammonia => GasFlags.Ammonia,
                Gas.NitrousOxide => GasFlags.NitrousOxide,
                Gas.Frezon => GasFlags.Frezon,
                _ => GasFlags.None,
            };

            if (msg.ExudeGases.HasFlag(flag))
                AppendGasLine(exudeGases, gas, exudeRatesMap.ContainsKey(gas) ? exudeRatesMap[gas] : null);

            if (msg.ConsumeGases.HasFlag(flag))
                AppendGasLine(consudeGases, gas, consumeRatesMap.ContainsKey(gas) ? consumeRatesMap[gas] : null);
        }

        // If there are explicit rates for gases not represented in flags, append them in advanced mode.
        if (isAdvanced && msg.ExudeGasRates != null)
        {
            foreach (var gr in msg.ExudeGasRates)
            {
                if (!msg.ExudeGases.HasFlag(gr.Gas.ToFlag()))
                    AppendGasLine(exudeGases, gr.Gas, gr.Rate);
            }
        }

        if (isAdvanced && msg.ConsumeGasRates != null)
        {
            foreach (var gr in msg.ConsumeGasRates)
            {
                if (!msg.ConsumeGases.HasFlag(gr.Gas.ToFlag()))
                    AppendGasLine(consudeGases, gr.Gas, gr.Rate);
            }
        }

        if (msg.IsTray)
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-plant", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));
        else if (msg.IsSwab)
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-swab", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));
        else
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-seed", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));
        // Basics
        PlantYield.Text = Loc.GetString("plant-analyzer-plant-yield-text", ("seedYield", $"{msg.SeedYield:D0}"));
        Potency.Text = Loc.GetString("plant-analyzer-plant-potency-text", ("seedPotency", $"{msg.SeedPotency:F0}"));
        Repeat.Text = Loc.GetString("plant-analyzer-plant-harvest-text", ("plantHarvestType", Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}").ToString()));
        Endurance.Text = Loc.GetString("plant-analyzer-plant-endurance-text", ("seedEndurance", $"{msg.Endurance:F0}"));
        Chemicals.Text = Loc.GetString("plant-analyzer-plant-chemistry-text", ("seedChem", chemString));
        ExudeGases.Text = Loc.GetString("plant-analyzer-plant-exude-text", ("gases", exudeGases.Length == 0 ? Loc.GetString("plant-analyzer-plant-gases-none") : exudeGases.ToString()));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-plant-consume-text", ("gases", consudeGases.Length == 0 ? Loc.GetString("plant-analyzer-plant-gases-none") : consudeGases.ToString()));
        Lifespan.Text = Loc.GetString("plant-analyzer-plant-lifespan-text", ("lifespan", $"{msg.Lifespan:F1}"));
        Maturation.Text = Loc.GetString("plant-analyzer-plant-maturation-text", ("maturation", $"{msg.Maturation:F1}"));
        Production.Text = Loc.GetString("plant-analyzer-plant-production-text", ("production", $"{msg.Production:F1}"));
        GrowthStages.Text = Loc.GetString("plant-analyzer-plant-growthstages-text", ("growthStages", $"{msg.GrowthStages:D0}"));
        // Tolerances
        var adv = msg.AdvancedInfo;
        NutrientUsage.Text = Loc.GetString("plant-analyzer-tolerance-nutrient-usage", ("nutrientUsage", adv is null ? "-" : $"{adv.Value.NutrientConsumption:F2}"));
        WaterUsage.Text = Loc.GetString("plant-analyzer-tolerance-water-usage", ("waterUsage", adv is null ? "-" : $"{adv.Value.WaterConsumption:F2}"));
        IdealHeat.Text = Loc.GetString("plant-analyzer-tolerance-ideal-heat", ("idealHeat", adv is null ? "-" : $"{adv.Value.IdealHeat:F0}"));
        HeatTolerance.Text = Loc.GetString("plant-analyzer-tolerance-heat-tolerance", ("heatTolerance", adv is null ? "-" : $"{adv.Value.HeatTolerance:F1}"));
        IdealLight.Text = Loc.GetString("plant-analyzer-tolerance-ideal-light", ("idealLight", adv is null ? "-" : $"{adv.Value.IdealLight:F1}"));
        LightTolerance.Text = Loc.GetString("plant-analyzer-tolerance-light-tolerance", ("lightTolerance", adv is null ? "-" : $"{adv.Value.LightTolerance:F1}"));
        ToxinsTolerance.Text = Loc.GetString("plant-analyzer-tolerance-toxin-tolerance", ("toxinsTolerance", adv is null ? "-" : $"{adv.Value.ToxinsTolerance:F1}"));
        LowPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-low-pressure", ("lowPressureTolerance", adv is null ? "-" : $"{adv.Value.LowPressureTolerance:F1}")); ;
        HighPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-high-pressure", ("highPressureTolerance", adv is null ? "-" : $"{adv.Value.HighPressureTolerance:F1}"));
        PestTolerance.Text = Loc.GetString("plant-analyzer-tolerance-pest-tolerance", ("pestTolerance", adv is null ? "-" : $"{adv.Value.PestTolerance:F1}"));
        WeedTolerance.Text = Loc.GetString("plant-analyzer-tolerance-weed-tolerance", ("weedTolerance", adv is null ? "-" : $"{adv.Value.WeedTolerance:F1}"));
        // Misc

        if (adv != null)
        {
            var advInst = adv.Value;
            StringBuilder mutations = new();
            if (advInst.Mutations.HasFlag(MutationFlags.TurnIntoKudzu))
            {
                mutations.Append(IndentedNewline);
                mutations.Append(Loc.GetString("plant-analyzer-mutation-turnintokudzu"));
            }
            if (advInst.Mutations.HasFlag(MutationFlags.Seedless))
            {
                mutations.Append(IndentedNewline);
                mutations.Append(Loc.GetString("plant-analyzer-mutation-seedless"));
            }
            if (advInst.Mutations.HasFlag(MutationFlags.Ligneous))
            {
                mutations.Append(IndentedNewline);
                mutations.Append(Loc.GetString("plant-analyzer-mutation-ligneous"));
            }
            if (advInst.Mutations.HasFlag(MutationFlags.CanScream))
            {
                mutations.Append(IndentedNewline);
                mutations.Append(Loc.GetString("plant-analyzer-mutation-canscream"));
            }

            Traits.Text = Loc.GetString("plant-analyzer-plant-mutations-text", ("traits", mutations.ToString()));
        }
        else
        {
            Traits.Text = Loc.GetString("plant-analyzer-plant-mutations-text", ("traits", "-"));
        }

        StringBuilder speciation = new();
        if (msg.Speciation is null)
        {
            speciation.Append("-");
        }
        else
        {
            foreach (var species in msg.Speciation)
            {
                speciation.Append(IndentedNewline);
                speciation.Append(Loc.GetString(species));
            }
        }

        PlantSpeciation.Text = Loc.GetString("plant-analyzer-plant-speciation-text", ("speciation", speciation.ToString()));
        }
        catch (Exception e)
        {
            // Prevent unhandled exceptions from bubbling out of UI populate
            NoData.Visible = true;
            Traits.Text = e.Message;
        }
    }

        private StringBuilder GetStringFromGasFlags(GasFlags flags, HashSet<Gas>? exclude = null)
    {
        StringBuilder output = new();
        if (flags.HasFlag(GasFlags.Nitrogen))
        {
            if (exclude == null || !exclude.Contains(Gas.Nitrogen))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-nitrogen"));
            }
        }
        if (flags.HasFlag(GasFlags.Oxygen))
        {
            if (exclude == null || !exclude.Contains(Gas.Oxygen))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-oxygen"));
            }
        }
        if (flags.HasFlag(GasFlags.CarbonDioxide))
        {
            if (exclude == null || !exclude.Contains(Gas.CarbonDioxide))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-co2"));
            }
        }
        if (flags.HasFlag(GasFlags.Plasma))
        {
            if (exclude == null || !exclude.Contains(Gas.Plasma))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-plasma"));
            }
        }
        if (flags.HasFlag(GasFlags.Tritium))
        {
            if (exclude == null || !exclude.Contains(Gas.Tritium))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-tritium"));
            }
        }
        if (flags.HasFlag(GasFlags.WaterVapor))
        {
            if (exclude == null || !exclude.Contains(Gas.WaterVapor))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-water-vapor"));
            }
        }
        if (flags.HasFlag(GasFlags.Ammonia))
        {
            if (exclude == null || !exclude.Contains(Gas.Ammonia))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-ammonia"));
            }
        }
        if (flags.HasFlag(GasFlags.NitrousOxide))
        {
            if (exclude == null || !exclude.Contains(Gas.NitrousOxide))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-n2o"));
            }
        }
        if (flags.HasFlag(GasFlags.Frezon))
        {
            if (exclude == null || !exclude.Contains(Gas.Frezon))
            {
            output.Append(IndentedNewline);
            output.Append(Loc.GetString("gases-frezon"));
            }
        }
        return output;
    }

    private string GetGasName(Gas gas)
    {
        return gas switch
        {
            Gas.Nitrogen => Loc.GetString("gases-nitrogen"),
            Gas.Oxygen => Loc.GetString("gases-oxygen"),
            Gas.CarbonDioxide => Loc.GetString("gases-co2"),
            Gas.Plasma => Loc.GetString("gases-plasma"),
            Gas.Tritium => Loc.GetString("gases-tritium"),
            Gas.WaterVapor => Loc.GetString("gases-water-vapor"),
            Gas.Ammonia => Loc.GetString("gases-ammonia"),
            Gas.NitrousOxide => Loc.GetString("gases-n2o"),
            Gas.Frezon => Loc.GetString("gases-frezon"),
            _ => gas.ToString(),
        };
    }
}
